## Examples

In [2]:
import school_choice as sc
import numpy as np
import csv

Succesful test running data that was embedded in the class for testing purposes . 
The output at each step of my implementation is shown below. 

Important: All data is converted to 0-based, and all output is as well

In the data for thist test and all the other tests, note that in the 1-based indexed original data, 0s indicate that the student does not intend to apply to the school. This is necessary to
have valid rectangular matrices. In the case of data imported from a CSV table, 0s are easier to work with than simply having empty spaces

In [4]:
test1 = sc.School_Choice(3,8) #(num_students, num_schools)
test1.read_data('embedded test', "")
test1.execute()
test1.print_result_by_schools()


read_data(): data_source is  embedded test
Input data after converted to 0-based indexing:
student_data_input:
[[ 0  1  2]
 [ 0  2  1]
 [ 2  0  1]
 [ 0  2  1]
 [ 1  2  0]
 [ 2  0  1]
 [ 1  0  2]
 [ 1 -1 -1]]
school_data_input:
[[ 0  1  2  3  4  5  6 -1]
 [ 0  2  3  6  4  5  1 -1]
 [ 0  5  3  6  4  1 -1 -1]]
school_unacceptable_input:
[[-1 -1 -1 -1 -1 -1 -1 -1]
 [ 7 -1 -1 -1 -1 -1 -1 -1]
 [ 2 -1 -1 -1 -1 -1 -1 -1]]
school_quota_input:
[2 3 3]

 students data:
self.students[0].prefs [0, 1, 2]
self.students[0].num_school_choices 3
self.students[1].prefs [0, 2, 1]
self.students[1].num_school_choices 3
self.students[2].prefs [2, 0, 1]
self.students[2].num_school_choices 3
self.students[3].prefs [0, 2, 1]
self.students[3].num_school_choices 3
self.students[4].prefs [1, 2, 0]
self.students[4].num_school_choices 3
self.students[5].prefs [2, 0, 1]
self.students[5].num_school_choices 3
self.students[6].prefs [1, 0, 2]
self.students[6].num_school_choices 3
self.students[7].prefs [1, -1, -1]
self

Succesful test using data from CSV files. The files used for testing are also found in the repo. 

In [5]:
test2 = sc.School_Choice(3,8)
test2.read_data('files', ["student_data1.csv", "school_data1.csv", "school_unacceptable_data1.csv", "school_quota1.csv"])
test2.execute()
test2.print_result_by_schools()


read_data(): data_source is  files

read_data(): list of input files:
student_data1.csv
school_data1.csv
school_unacceptable_data1.csv
school_quota1.csv
read_data(): succefully open 4 input files.
Input data after converted to 0-based indexing:
student_data_input:
[[0 1 2]
 [0 2 1]
 [2 0 1]
 [0 2 1]
 [1 2 0]
 [2 0 1]
 [1 0 2]
 [2 1 0]]
school_data_input:
[[0 1 2 3 4 5 6 7]
 [0 2 3 6 7 4 5 1]
 [0 5 2 3 6 4 1 7]]
school_unacceptable_input:
[[-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]
school_quota_input:
[2 3 3]

 students data:
self.students[0].prefs [0, 1, 2]
self.students[0].num_school_choices 3
self.students[1].prefs [0, 2, 1]
self.students[1].num_school_choices 3
self.students[2].prefs [2, 0, 1]
self.students[2].num_school_choices 3
self.students[3].prefs [0, 2, 1]
self.students[3].num_school_choices 3
self.students[4].prefs [1, 2, 0]
self.students[4].num_school_choices 3
self.students[5].prefs [2, 0, 1]
self.students[5].num_school_choices 3
self

Succesful test defining matrices manually and passing them

In [7]:
#Rows represent students. Columbs represents students' preferences over schools. 
student_data = np.array(([1, 2, 3],
                                  [1, 3, 2],
                                  [3, 1, 2],
                                  [1, 3, 2],
                                  [2, 3, 1],
                                  [3, 1, 2],
                                  [2, 1, 3],
                                  [2, 0, 0]
                                 ))
    
# Rows represent schools. Columns represent school's preferences over students.
school_data = np.array(([1, 2, 3 ,4, 5, 6, 7, 0],
                                 [1, 3, 4, 7, 5, 6, 2, 0],
                                 [1, 6, 4, 7, 5, 2, 0, 0],
                                ))
                             
# Rows represent schools. Columns represent school's unacceptable students.
school_unacceptable_data = np.array(([0, 0, 0 ,0, 0, 0, 0, 0],
                                 [8, 0, 0 ,0, 0, 0, 0, 0],
                                 [3, 0, 0 ,0, 0, 0, 0, 0],
                                ))           
                          
#Schools' quata     
#_test_school_quota_input = np.array(([3, 3, 3]))                                                     
school_quota = np.array(([2, 3, 3]))                                                     
    
test3 = sc.School_Choice(3,8)
test3.read_data('input_data', "", student_data, school_data, school_unacceptable_data, school_quota )
test3.execute()
test3.print_result_by_schools()


read_data(): data_source is  input_data
Input data after converted to 0-based indexing:
student_data_input:
[[ 0  1  2]
 [ 0  2  1]
 [ 2  0  1]
 [ 0  2  1]
 [ 1  2  0]
 [ 2  0  1]
 [ 1  0  2]
 [ 1 -1 -1]]
school_data_input:
[[ 0  1  2  3  4  5  6 -1]
 [ 0  2  3  6  4  5  1 -1]
 [ 0  5  3  6  4  1 -1 -1]]
school_unacceptable_input:
[[-1 -1 -1 -1 -1 -1 -1 -1]
 [ 7 -1 -1 -1 -1 -1 -1 -1]
 [ 2 -1 -1 -1 -1 -1 -1 -1]]
school_quota_input:
[2 3 3]

 students data:
self.students[0].prefs [0, 1, 2]
self.students[0].num_school_choices 3
self.students[1].prefs [0, 2, 1]
self.students[1].num_school_choices 3
self.students[2].prefs [2, 0, 1]
self.students[2].num_school_choices 3
self.students[3].prefs [0, 2, 1]
self.students[3].num_school_choices 3
self.students[4].prefs [1, 2, 0]
self.students[4].num_school_choices 3
self.students[5].prefs [2, 0, 1]
self.students[5].num_school_choices 3
self.students[6].prefs [1, 0, 2]
self.students[6].num_school_choices 3
self.students[7].prefs [1, -1, -1]
self.st